service:
  debug: true
  logFile: "user_meta_service.log"
  
database:
  address: "127.0.0.1:27017"
  db: "UserDB"
  collection: "UserMetaCollection"

accountStatuses:
    verified: "Verfied" # When the account is verified with email
    unverified: "Unverified" # When the account is not verified with email
    deleted: "Deleted" # When the account is deleted